### ISSUE TITLE
Can't install beacause the update site is unavailable

### ISSUE THREAD

**Issue by jabby** [sebthom/extra-syntax-highlighting-eclipse-plugin#141] opened 2024-10-10 01:02 UTC
Hello, 

I tried to install your plugin through Eclipse Marketplace and directly with the link provided in REAME.md

Seems that update site is not available. I always got a `400` http error code when accessing the update site through my browser.

**Comment by sebthom** [comment] 2024-10-10 11:13
The update site seems to work for me. it is expected that you get a 400 when using a browser. just use that URL in Eclipse.

**Comment by jabby** [comment] 2024-10-10 16:38
Ok I can install your plugin with  the link directly in 'Install new software' dialog.

But I still can't use the marketplace entry to install your plugin. See following images for illustration.

![image](https://github.com/user-attachments/assets/a9f5242e-886a-4b62-b15c-e9f70488bee7)
![image](https://github.com/user-attachments/assets/40ca4364-d638-460e-886d-03f3ef56603b)
![image](https://github.com/user-attachments/assets/71024486-6666-4a16-bdee-d935716b8e49)

Should I close this issue and open a new one?

**Comment by sebthom** [comment] 2024-10-10 16:54
Hm, I cannot reproduce this. I just installed a fresh copy of eclipse 2024-09 and could install from https://raw.githubusercontent.com/sebthom/extra-syntax-highlighting-eclipse-plugin/updatesite with no problems.

What does the error log show?

**Comment by sebthom** [comment] 2024-10-26 11:21
Closing because of no user feedback. Feel free to re-open if issue persists.

**Closed by sebthom** 2024-10-26 11:21 UTC
